/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller_Laundry;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import DAO.DAO;
import Model.Model;
import Implement.Implement;
import Tabel_Model.Tabel_Model;


/**
 *
 * @author ASUS
 */
public class ViewLaundry extends javax.swing.JFrame {
    Controller_Laundry controller_Laundry;
    Implement implement;
    /**
     * Creates new form View2
     */
    public ViewLaundry() {
        initComponents();
        
        controller_Laundry = new Controller_Laundry(this);
        implement = new DAO();
        controller_Laundry.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        panel_awal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btntambah = new javax.swing.JButton();
        btnlihat = new javax.swing.JButton();
        panel_utama = new javax.swing.JPanel();
        paneltampildata = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        paneltambahdata = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tidtransaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tberat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tharga = new javax.swing.JTextField();
        ttotal = new javax.swing.JTextField();
        btbatal1 = new javax.swing.JButton();
        bttambah1 = new javax.swing.JButton();
        cbxjenis = new javax.swing.JComboBox<>();
        panelupdatedata = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tidtransaksi1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tnama1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tberat1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tharga1 = new javax.swing.JTextField();
        ttotal1 = new javax.swing.JTextField();
        btbatal2 = new javax.swing.JButton();
        bttambah2 = new javax.swing.JButton();
        cbxjenis1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelutama.setLayout(new java.awt.CardLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Laundry Insyaallah Amanah");

        btntambah.setBackground(new java.awt.Color(255, 255, 255));
        btntambah.setText("Tambah Data");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnlihat.setBackground(new java.awt.Color(255, 255, 255));
        btnlihat.setText("Lihat Data");
        btnlihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlihatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_awalLayout = new javax.swing.GroupLayout(panel_awal);
        panel_awal.setLayout(panel_awalLayout);
        panel_awalLayout.setHorizontalGroup(
            panel_awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_awalLayout.createSequentialGroup()
                .addGroup(panel_awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_awalLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel7))
                    .addGroup(panel_awalLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_awalLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_awalLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnlihat, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        panel_awalLayout.setVerticalGroup(
            panel_awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_awalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlihat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        panelutama.add(panel_awal, "card2");

        panel_utama.setLayout(new java.awt.CardLayout());

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Laundry");

        btback.setBackground(new java.awt.Color(255, 255, 255));
        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 255, 255));
        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btedit.setBackground(new java.awt.Color(255, 255, 255));
        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneltampildataLayout = new javax.swing.GroupLayout(paneltampildata);
        paneltampildata.setLayout(paneltampildataLayout);
        paneltampildataLayout.setHorizontalGroup(
            paneltampildataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltampildataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltampildataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltampildataLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneltampildataLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneltampildataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        paneltampildataLayout.setVerticalGroup(
            paneltampildataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltampildataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(paneltampildataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneltampildataLayout.createSequentialGroup()
                        .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(520, Short.MAX_VALUE))
        );

        panel_utama.add(paneltampildata, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Tambah Data Transaksi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID Transaksi");

        tidtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidtransaksiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Harga Per Kilo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah Berat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Layanan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nama Customer");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total");

        btbatal1.setBackground(new java.awt.Color(255, 255, 255));
        btbatal1.setText("Batal");
        btbatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatal1ActionPerformed(evt);
            }
        });

        bttambah1.setBackground(new java.awt.Color(255, 255, 255));
        bttambah1.setText("Tambah");
        bttambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambah1ActionPerformed(evt);
            }
        });

        cbxjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- pilih jenis layanan --", "dry cleaning", "reguler", "oneday", "cuci karpet" }));
        cbxjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxjenisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                            .addComponent(tidtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tnama)
                                .addComponent(tberat)
                                .addComponent(tharga)
                                .addComponent(ttotal)
                                .addComponent(cbxjenis, 0, 606, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(bttambah1)
                        .addGap(31, 31, 31)
                        .addComponent(btbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tidtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(cbxjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tberat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneltambahdataLayout = new javax.swing.GroupLayout(paneltambahdata);
        paneltambahdata.setLayout(paneltambahdataLayout);
        paneltambahdataLayout.setHorizontalGroup(
            paneltambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltambahdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(paneltambahdataLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltambahdataLayout.setVerticalGroup(
            paneltambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltambahdataLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        panel_utama.add(paneltambahdata, "card2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setText("Edit Data Transaksi");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ID Transaksi");

        tidtransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidtransaksi1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Harga Per Kilo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Jumlah Berat");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Jenis Layanan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Nama Customer");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Total");

        btbatal2.setBackground(new java.awt.Color(255, 255, 255));
        btbatal2.setText("Batal");
        btbatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatal2ActionPerformed(evt);
            }
        });

        bttambah2.setBackground(new java.awt.Color(255, 255, 255));
        bttambah2.setText("Edit");
        bttambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambah2ActionPerformed(evt);
            }
        });

        cbxjenis1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- pilih jenis layanan --", "dry cleaning", "reguler", "oneday", "cuci karpet" }));
        cbxjenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxjenis1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                            .addComponent(tidtransaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(jLabel16)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tnama1)
                                .addComponent(tberat1)
                                .addComponent(tharga1)
                                .addComponent(ttotal1)
                                .addComponent(cbxjenis1, 0, 606, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(bttambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tidtransaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(cbxjenis1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tberat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelupdatedataLayout = new javax.swing.GroupLayout(panelupdatedata);
        panelupdatedata.setLayout(panelupdatedataLayout);
        panelupdatedataLayout.setHorizontalGroup(
            panelupdatedataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelupdatedataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelupdatedataLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelupdatedataLayout.setVerticalGroup(
            panelupdatedataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelupdatedataLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        panel_utama.add(panelupdatedata, "card2");

        panelutama.add(panel_utama, "card2");

        getContentPane().add(panelutama, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        controller_Laundry.isiField(tabeldata.getSelectedRow());
    }//GEN-LAST:event_tabeldataMouseClicked

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        // TODO add your handling code here:
        panelutama.removeAll();
        panelutama.repaint();
        panelutama.revalidate();

        panelutama.add(panel_awal);
        panelutama.repaint();
        panelutama.revalidate();
    }//GEN-LAST:event_btbackActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        controller_Laundry.delete();
        controller_Laundry.isiTable();
        controller_Laundry.reset();
    }//GEN-LAST:event_bthapusActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        panelutama.removeAll();
        panelutama.repaint();
        panelutama.revalidate();

        panelutama.add(panelupdatedata);
        panelutama.repaint();
        panelutama.revalidate();
        controller_Laundry.isiField(tabeldata.getSelectedRow());
        tidtransaksi1.setEnabled(false);
       

      
  
        
    }//GEN-LAST:event_bteditActionPerformed

    private void tidtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidtransaksiActionPerformed

    private void btbatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatal1ActionPerformed
        // TODO add your handling code here:
       tampilPanel();
       controller_Laundry.reset();
    }//GEN-LAST:event_btbatal1ActionPerformed

    private void bttambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambah1ActionPerformed
        // TODO add your handling code here:
        controller_Laundry.insert();
        controller_Laundry.isiTable();
        resetForm();
        tampilPanel();
        
    }//GEN-LAST:event_bttambah1ActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here
        panelutama.removeAll();
        panelutama.repaint();
        panelutama.revalidate();

        panelutama.add(paneltambahdata);
        panelutama.repaint();
        panelutama.revalidate();
        
        tidtransaksi.setText(implement.urutan());
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnlihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlihatActionPerformed
        // TODO add your handling code here:
        panelutama.removeAll();
        panelutama.repaint();
        panelutama.revalidate();

        panelutama.add(paneltampildata);
        panelutama.repaint();
        panelutama.revalidate();
    }//GEN-LAST:event_btnlihatActionPerformed

    private void tidtransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidtransaksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidtransaksi1ActionPerformed

    private void btbatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatal2ActionPerformed
        // TODO add your handling code here:
       tampilPanel();
    }//GEN-LAST:event_btbatal2ActionPerformed

    private void bttambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambah2ActionPerformed
        // TODO add your handling code here:
        controller_Laundry.update();
        controller_Laundry.isiTable();
         resetForm();
         tampilPanel();
    }//GEN-LAST:event_bttambah2ActionPerformed

    private void cbxjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxjenisActionPerformed
        // TODO add your handling code here:
        
        String selectedValue = cbxjenis.getSelectedItem().toString();
       if(selectedValue == "dry cleaning"){
           tharga.setText("5000");
           
       }
       else if(selectedValue == "reguler"){
           tharga.setText("4000");
           
       }
       
       else if(selectedValue == "oneday"){
           tharga.setText("9000");
           
       }
       else if(selectedValue == "cuci karpet"){
           tharga.setText("7000");
           
       }
       
    }//GEN-LAST:event_cbxjenisActionPerformed

    private void cbxjenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxjenis1ActionPerformed
        // TODO add your handling code here:
         String selectedValue = cbxjenis1.getSelectedItem().toString();
       if(selectedValue == "dry cleaning"){
           tharga1.setText("5000");
           
       }
       else if(selectedValue == "reguler"){
           tharga1.setText("4000");
           
       }
       
       else if(selectedValue == "oneday"){
           tharga1.setText("9000");
           
       }
       else if(selectedValue == "cuci karpet"){
           tharga1.setText("7000");
           
       }
    }//GEN-LAST:event_cbxjenis1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btbatal1;
    private javax.swing.JButton btbatal2;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btnlihat;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton bttambah1;
    private javax.swing.JButton bttambah2;
    private javax.swing.JComboBox<String> cbxjenis;
    private javax.swing.JComboBox<String> cbxjenis1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_awal;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel paneltambahdata;
    private javax.swing.JPanel paneltampildata;
    private javax.swing.JPanel panelupdatedata;
    private javax.swing.JPanel panelutama;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField tberat;
    private javax.swing.JTextField tberat1;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tharga1;
    private javax.swing.JTextField tidtransaksi;
    private javax.swing.JTextField tidtransaksi1;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnama1;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField ttotal1;
    // End of variables declaration//GEN-END:variables

    private void aktif(){
    tidtransaksi.setEnabled(true);
    tnama.setEnabled(true);
    
}    
    

private void resetForm(){
    btntambah.requestFocus();
    btntambah.setText("Tambah");
    tidtransaksi.setText("");
    tnama.setText("");
    cbxjenis.setSelectedItem("");
    tberat.setText("");
    tharga.setText("");
    ttotal.setText("");

}

private void resetForm1(){
    
    
    tidtransaksi1.setText("");
    tnama1.setText("");
    cbxjenis1.setSelectedItem("");
    tberat1.setText("");
    tharga1.setText("");
    ttotal1.setText("");

}

private void tampilPanel(){
    panelutama.removeAll();
    panelutama.add(panel_awal);
    panelutama.repaint();
    panelutama.revalidate();
}




   

    public JButton getBtbatal2() {
        return btbatal2;
    }

    public void setBtbatal2(JButton btbatal2) {
        this.btbatal2 = btbatal2;
    }

    public JButton getBttambah2() {
        return bttambah2;
    }

    public void setBttambah2(JButton bttambah2) {
        this.bttambah2 = bttambah2;
    }

    public JComboBox<String> getCbxjenis1() {
        return cbxjenis1;
    }

    public void setCbxjenis1(JComboBox<String> cbxjenis1) {
        this.cbxjenis1 = cbxjenis1;
    }

    public JTextField getTberat1() {
        return tberat1;
    }

    public void setTberat1(JTextField tberat1) {
        this.tberat1 = tberat1;
    }

    public JTextField getTharga1() {
        return tharga1;
    }

    public void setTharga1(JTextField tharga1) {
        this.tharga1 = tharga1;
    }

    public JTextField getTidtransaksi1() {
        return tidtransaksi1;
    }
    
    

    public void setTidtransaksi1(JTextField tidtransaksi1) {
        this.tidtransaksi1 = tidtransaksi1;
    }

    public JTextField getTnama1() {
        return tnama1;
    }

    public void setTnama1(JTextField tnama1) {
        this.tnama1 = tnama1;
    }

    public JTextField getTtotal1() {
        return ttotal1;
    }

    public void setTtotal1(JTextField ttotal1) {
        this.ttotal1 = ttotal1;
    }
    
    public JButton getBtback() {
        return btback;
    }

    public void setBtback(JButton btback) {
        this.btback = btback;
    }

    public JButton getBtbatal1() {
        return btbatal1;
    }

    public void setBtbatal1(JButton btbatal1) {
        this.btbatal1 = btbatal1;
    }

    public JButton getBtedit() {
        return btedit;
    }

    public void setBtedit(JButton btedit) {
        this.btedit = btedit;
    }

    public JButton getBthapus() {
        return bthapus;
    }

    public void setBthapus(JButton bthapus) {
        this.bthapus = bthapus;
    }

    public JButton getBtnlihat() {
        return btnlihat;
    }

    public void setBtnlihat(JButton btnlihat) {
        this.btnlihat = btnlihat;
    }

    public JButton getBtntambah() {
        return btntambah;
    }

    public void setBtntambah(JButton btntambah) {
        this.btntambah = btntambah;
    }

    public JButton getBttambah1() {
        return bttambah1;
    }

    public void setBttambah1(JButton bttambah1) {
        this.bttambah1 = bttambah1;
    }

    public JComboBox<String> getCbxjenis() {
        return cbxjenis;
    }

    public void setCbxjenis(JComboBox<String> cbxjenis) {
        this.cbxjenis = cbxjenis;
    }

    public JTable getTabeldata() {
        return tabeldata;
    }

    public void setTabeldata(JTable tabeldata) {
        this.tabeldata = tabeldata;
    }

    public JTextField getTberat() {
        return tberat;
    }

    public void setTberat(JTextField tberat) {
        this.tberat = tberat;
    }

    public JTextField getTharga() {
        return tharga;
    }

    public void setTharga(JTextField tharga) {
        this.tharga = tharga;
    }

    public JTextField getTidtransaksi() {
        return tidtransaksi;
    }

    public void setTidtransaksi(JTextField tidtransaksi) {
        this.tidtransaksi = tidtransaksi;
    }

    public JTextField getTnama() {
        return tnama;
    }

    public void setTnama(JTextField tnama) {
        this.tnama = tnama;
    }

    public JTextField getTtotal() {
        return ttotal;
    }

    public void setTtotal(JTextField ttotal) {
        this.ttotal = ttotal;
        
    }

}

